import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes';
import adminAuthRoutes from '../modules/adminAuth/adminAuth.routes';
import userRoutes from '../modules/users/user.routes';
import adminRoutes from '../modules/admins/admin.routes';
import roleRoutes from '../modules/admins/role.routes';
import productRoutes from '../modules/products/product.routes';
import categoryRoutes from '../modules/categories/category.routes';
import collectionRoutes from '../modules/collections/collection.routes';
import bannerRoutes from '../modules/banners/banner.routes';
import contentRoutes from '../modules/content/content.routes';
import blogRoutes from '../modules/blogs/blog.routes';
import shippingRoutes from '../modules/shipping/shipping.routes';
import cartRoutes from '../modules/cart/cart.routes';
import wishlistRoutes from '../modules/wishlist/wishlist.routes';
import addressRoutes from '../modules/addresses/address.routes';
import orderRoutes from '../modules/orders/order.routes';
import reviewRoutes from '../modules/reviews/review.routes';
import couponRoutes from '../modules/coupons/coupon.routes';
import customBlouseRoutes from '../modules/customBlouse/customBlouse.routes';
import analyticsRoutes from '../modules/analytics/analytics.routes';
import settingsRoutes from '../modules/settings/settings.routes';
import uploadRoutes from '../modules/uploads/upload.routes';
import supportRoutes from '../modules/support/support.routes';
import notificationRoutes from '../modules/notifications/notification.routes';
import auditLogRoutes from '../modules/auditLogs/auditLog.routes';
import paymentRoutes from '../modules/payments/payment.routes';
import reconciliationRoutes from '../modules/reconciliation/reconciliation.routes';
import idempotencyRoutes from '../modules/payments/idempotency.routes';
import boutiqueRoutes from '../modules/boutique/boutique.routes';
import measurementRoutes from '../modules/measurements/measurement.routes';

import customBlouseOptionRoutes from '../modules/customBlouse/customBlouseOption.routes';
import { cmsRoutes, adminCmsRoutes } from '../modules/cms/cms.routes';
import ownerAuthRoutes from '../modules/ownerAuth/ownerAuth.routes';
import ownerAdminRoutes from '../modules/ownerAuth/ownerAdmin.routes';
import { tailorAuthRoutes } from '../modules/tailorAuth/tailorAuth.routes';
import { tailorAdminRoutes } from '../modules/tailors/tailor.routes';
import { adminWorkflowRoutes, tailorDashboardRoutes } from '../modules/workflows/workflow.routes';
import managerAuthRoutes from '../modules/managerAuth/managerAuth.routes';
import managerRoutes from '../modules/managers/manager.routes';
import marketingRoutes from '../modules/marketing/marketing.routes';
import attendanceRoutes from '../modules/attendance/attendance.routes';
import workforceRoutes from '../modules/workforce/workforce.routes';
import legalRoutes from '../modules/legal/legalPage.routes';
import healthRoutes from '../modules/monitoring/health.routes';
import seoRoutes from '../modules/seo/seo.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/admin-auth', adminAuthRoutes);
router.use('/users', userRoutes);
router.use('/admins', adminRoutes);
router.use('/roles', roleRoutes);
router.use('/products', productRoutes);
router.use('/categories', categoryRoutes);
router.use('/collections', collectionRoutes);
router.use('/banners', bannerRoutes);
router.use('/content', contentRoutes);
router.use('/blogs', blogRoutes);
router.use('/shipping', shippingRoutes);
router.use('/cart', cartRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/addresses', addressRoutes);
router.use('/orders', orderRoutes);
router.use('/reviews', reviewRoutes);
router.use('/coupons', couponRoutes);
router.use('/custom-blouse', customBlouseRoutes);
router.use('/custom-requests', customBlouseRoutes);
router.use('/custom-blouse-options', customBlouseOptionRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/settings', settingsRoutes);
router.use('/uploads', uploadRoutes);
router.use('/support', supportRoutes);
router.use('/notifications', notificationRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/payments', paymentRoutes);
router.use('/admin/reconciliation', reconciliationRoutes);
router.use('/admin/idempotency', idempotencyRoutes);
router.use('/boutique', boutiqueRoutes);
router.use('/measurements', measurementRoutes);
router.use('/cms', cmsRoutes);
router.use('/admin/cms', adminCmsRoutes);
router.use('/owner-auth', ownerAuthRoutes);
router.use('/admin/boutique-owners', ownerAdminRoutes);
router.use('/tailor-auth', tailorAuthRoutes);
router.use('/admin/tailors', tailorAdminRoutes);
router.use('/admin/workflows', adminWorkflowRoutes);
router.use('/tailor-dashboard/tasks', tailorDashboardRoutes);
router.use('/manager-auth', managerAuthRoutes);
router.use('/admin/managers', managerRoutes);
router.use('/marketing', marketingRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/workforce', workforceRoutes);
router.use('/legal', legalRoutes);
router.use('/monitoring', healthRoutes);
router.use('/seo', seoRoutes);

export default router;
