export const USER_ROLES = {
  CUSTOMER: 'customer',
} as const;

export const ADMIN_ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  CATALOG_MANAGER: 'catalog_manager',
  ORDER_MANAGER: 'order_manager',
  SUPPORT_MANAGER: 'support_manager',
  MARKETING_MANAGER: 'marketing_manager',
  FINANCE_VIEWER: 'finance_viewer',
} as const;

export const PERMISSIONS = {
  // Admin management
  MANAGE_ADMINS: 'manage_admins',
  MANAGE_ROLES: 'manage_roles',

  // Catalog
  MANAGE_PRODUCTS: 'manage_products',
  MANAGE_CATEGORIES: 'manage_categories',
  MANAGE_COLLECTIONS: 'manage_collections',
  MANAGE_BANNERS: 'manage_banners',

  // Commerce
  MANAGE_ORDERS: 'manage_orders',
  MANAGE_COUPONS: 'manage_coupons',
  MANAGE_PAYMENTS: 'manage_payments',
  MANAGE_SHIPPING: 'manage_shipping',

  // Content
  MANAGE_CONTENT: 'manage_content',

  // Users
  MANAGE_USERS: 'manage_users',

  // Custom blouse
  MANAGE_CUSTOM_BLOUSE: 'manage_custom_blouse',

  // Reviews
  MANAGE_REVIEWS: 'manage_reviews',

  // Analytics
  VIEW_ANALYTICS: 'view_analytics',

  // Settings
  MANAGE_SETTINGS: 'manage_settings',

  // Support
  MANAGE_SUPPORT: 'manage_support',

  // Audit
  VIEW_AUDIT_LOGS: 'view_audit_logs',

  // Media
  MANAGE_MEDIA: 'manage_media',

  // Notifications
  MANAGE_NOTIFICATIONS: 'manage_notifications',
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ADMIN_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ADMIN_ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_PRODUCTS, PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_COLLECTIONS, PERMISSIONS.MANAGE_BANNERS,
    PERMISSIONS.MANAGE_ORDERS, PERMISSIONS.MANAGE_COUPONS,
    PERMISSIONS.MANAGE_PAYMENTS, PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.MANAGE_USERS, PERMISSIONS.MANAGE_CUSTOM_BLOUSE,
    PERMISSIONS.MANAGE_REVIEWS, PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MANAGE_SUPPORT, PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_MEDIA, PERMISSIONS.MANAGE_NOTIFICATIONS,
    PERMISSIONS.MANAGE_SHIPPING,
  ],
  [ADMIN_ROLES.CATALOG_MANAGER]: [
    PERMISSIONS.MANAGE_PRODUCTS, PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_COLLECTIONS, PERMISSIONS.MANAGE_BANNERS,
    PERMISSIONS.MANAGE_MEDIA,
  ],
  [ADMIN_ROLES.ORDER_MANAGER]: [
    PERMISSIONS.MANAGE_ORDERS, PERMISSIONS.MANAGE_CUSTOM_BLOUSE,
    PERMISSIONS.MANAGE_SHIPPING,
  ],
  [ADMIN_ROLES.SUPPORT_MANAGER]: [
    PERMISSIONS.MANAGE_USERS, PERMISSIONS.MANAGE_SUPPORT,
    PERMISSIONS.MANAGE_CUSTOM_BLOUSE,
  ],
  [ADMIN_ROLES.MARKETING_MANAGER]: [
    PERMISSIONS.MANAGE_PRODUCTS, PERMISSIONS.MANAGE_BANNERS,
    PERMISSIONS.MANAGE_COUPONS, PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.MANAGE_MEDIA,
    PERMISSIONS.MANAGE_NOTIFICATIONS,
  ],
  [ADMIN_ROLES.FINANCE_VIEWER]: [
    PERMISSIONS.MANAGE_PAYMENTS, PERMISSIONS.VIEW_ANALYTICS,
  ],
};
