/**
 * Marketing ERP Enterprise Constants
 * Roles, Permissions, and SaaS Configuration
 */

export enum MARKETING_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  MARKETING_ADMIN = 'MARKETING_ADMIN',
  ANALYTICS_MANAGER = 'ANALYTICS_MANAGER',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  SUPPORT_MANAGER = 'SUPPORT_MANAGER'
}

export const MARKETING_PERMISSIONS = {
  VIEW_DASHBOARD: 'view_dashboard',
  MANAGE_CAMPAIGNS: 'manage_campaigns',
  MANAGE_BANNERS: 'manage_banners',
  MANAGE_COUPONS: 'manage_coupons',
  MANAGE_CONTENT: 'manage_content',
  VIEW_FINANCIALS: 'view_financials',
  VIEW_AI_INSIGHTS: 'view_ai_insights',
  MANAGE_INFLUENCERS: 'manage_influencers',
  MANAGE_AUTOMATION: 'manage_automation',
  VIEW_BEHAVIOR: 'view_behavior'
};

export const ROLE_PERMISSION_MATRIX: Record<MARKETING_ROLES, string[]> = {
  [MARKETING_ROLES.SUPER_ADMIN]: Object.values(MARKETING_PERMISSIONS),
  
  [MARKETING_ROLES.MARKETING_ADMIN]: [
    MARKETING_PERMISSIONS.VIEW_DASHBOARD,
    MARKETING_PERMISSIONS.MANAGE_CAMPAIGNS,
    MARKETING_PERMISSIONS.MANAGE_BANNERS,
    MARKETING_PERMISSIONS.MANAGE_COUPONS,
    MARKETING_PERMISSIONS.MANAGE_CONTENT,
    MARKETING_PERMISSIONS.MANAGE_INFLUENCERS
  ],
  
  [MARKETING_ROLES.ANALYTICS_MANAGER]: [
    MARKETING_PERMISSIONS.VIEW_DASHBOARD,
    MARKETING_PERMISSIONS.VIEW_FINANCIALS,
    MARKETING_PERMISSIONS.VIEW_AI_INSIGHTS,
    MARKETING_PERMISSIONS.VIEW_BEHAVIOR
  ],
  
  [MARKETING_ROLES.CONTENT_MANAGER]: [
    MARKETING_PERMISSIONS.VIEW_DASHBOARD,
    MARKETING_PERMISSIONS.MANAGE_CONTENT,
    MARKETING_PERMISSIONS.MANAGE_BANNERS
  ],
  
  [MARKETING_ROLES.SUPPORT_MANAGER]: [
    MARKETING_PERMISSIONS.VIEW_DASHBOARD,
    MARKETING_PERMISSIONS.VIEW_BEHAVIOR
  ]
};

// SaaS Multitenancy Config
export const SAAS_CONFIG = {
  TENANT_ISOLATION_STRATEGY: 'logical', // Logic-based filtering via tenantId
  DEFAULT_QUOTA: {
    MAX_CAMPAIGNS: 100,
    MAX_BANNERS: 20,
    MAX_AI_PREDICTIONS: 1000,
    RETENTION_DAYS: 365
  }
};
